### ISSUE TITLE
Update the pre-installed NDK version

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-docker/android-ndk#1]
Google changed the format of the distributed package from `.bin` to `.zip`, so it have to be changed accordingly - http://developer.android.com/ndk/downloads/index.html

**Comment by ThorstenBux** [comment]
Done and ready to merge 

https://github.com/bitrise-docker/android-ndk/pull/2

**Comment by viktorbenei** [comment]
Merged, thanks again!!

**Comment by viktorbenei** [comment]
Quick question, where did you see the new release? It's not listed on the official (AFAIK) version history page yet https://developer.android.com/ndk/downloads/index.html

**Comment by ThorstenBux** [comment]
;) Android Studio already downloads the version 12 so I just tried the URL. The initial idea was to update to NDK11 as your docker container still had NDK10 which was not working for me as I need at least 11.

**Comment by viktorbenei** [comment]
Thanks for the info! Strange that the official download page is not yet updated, I guess they just forgot to do that before propagating the new version to other sources (where Android Studio gets the version from).
