### ISSUE TITLE
cmake support

### ISSUE THREAD

**Issue by elias-pschernig** [bitrise-docker/android-ndk#16]
With the release of Android 2.2, Google deprecated ndk-build in favor of cmake. [1](https://developer.android.com/studio/projects/add-native-code.html)

We migrated our build to cmake instead of ndk-build - but that means we cannot build on the default bitrise any longer as it does not provide Google's new NDK tool-chain with their Android-cmake.

**Comment by viktorbenei** [comment]
Feel free to send a PR to replace the NDK with the latest version. You can test the whole Docker image locally, although it might be quite large (requires about 20GB disk space)

**Comment by viktorbenei** [comment]
Forgot to close this ticket, but the related PR was merge so this should now be fixed.

Thanks again @mickele and @elias-pschernig ! ;)
