### ISSUE TITLE
Failed to find CMake on Bitbucket's piplines

### ISSUE THREAD

**Issue by sergiuszkierat** [bitrise-docker/android-ndk#43]
I am trying to set up an empty android C++ project on bitbucket with piplines.

I have got [an exception](https://bitbucket.org/sergiuszkierat/android-ndk-pipeline/addon/pipelines/home#!/results/%7Be3f98a9b-4083-47c7-a123-79818b3ba947%7D)

```
Failed to find CMake.
  Install from Android Studio under File/Settings/Appearance & Behavior/System Settings/Android SDK/SDK Tools/CMake.
  Expected CMake executable at /opt/android-sdk-linux/cmake/bin/cmake
```

I am not sure if it is related directly to your docker image.

**Comment by viktorbenei** [comment]
Upgrade your Gradle plugin to 2.2.3 and provide the license, as discussed here: https://github.com/bitrise-io/build.issues/issues/33#issuecomment-279976448

**Comment by sergiuszkierat** [comment]
@viktorbenei Thanks for pointing out the solution. This is the [link](https://answers.atlassian.com/questions/43558078/answers/43559598) for anyone who struggles with it on Bitbucket.

**Comment by viktorbenei** [comment]
Just one note for this: the licenses can change @sergiuszkierat - so you'll have to replace them when you upgrade the related component's version. You can of course always just look up the license from your own Mac/PC, as described here: http://devcenter.bitrise.io/android/frequent-android-issues/#alternative-solution-for-the-license-error

Whether you actually copy the license files or just print them with `echo` is up to you ;)
